---
- hosts: all
  become: true
  vars:
    pkgs:
      - git
      - curl
      - htop
  tasks:
    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      loop: "{{ pkgs }}"
      when: ansible_os_family == 'Debian'
      register: apt_result

    - name: Show package install results
      debug:
        msg: "{{ item.item }}: changed={{ item.changed }}"
      loop: "{{ apt_result.results }}"
      when: ansible_os_family == 'Debian'
