---
- name: Webserver configuration
  hosts: web
  become: yes

  tasks:
    - name: Install Apache2
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Enable and start Apache2 service
      service:
        name: apache2
        state: started
        enabled: yes
