
version: '3.3'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: satvikdb
      POSTGRES_USER: redhat
      POSTGRES_PASSWORD: redhat
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"

  backend:
    build: ./backend
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: satvikdb
      DB_USER: redhat
      DB_PASSWORD: redhat
    ports:
      - "5001:5001"
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "5000:80"
    depends_on:
      - backend

volumes:
  postgres_data: